### ISSUE TITLE
IDE - Multiple definitions exist for class Yii

### ISSUE THREAD

**Issue by egretos** [takashiki/yii2-ide-helper#1]
![image here](https://user-images.githubusercontent.com/20698068/51896457-35ca1680-23b5-11e9-9563-1907c850c377.png)

How to fix it or disable this warning?

**Comment by loveorigami** [comment]
click on more.
You can see 2 or more yii implementations. 
For first  your working yii file - nothing to do. 
For next - mark as plain text in phpStorm.

**Comment by egretos** [comment]
> click on more.
> You can see 2 or more yii implementations.
> For first your working yii file - nothing to do.
> For next - mark as plain text in phpStorm.

Hey, its works! Thx!
